# Generated by Django 5.0 on 2023-12-24 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InstanceInstanceConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('raw_type', models.CharField(max_length=100)),
                ('limitation', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='ClassInstanceRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.class')),
                ('instance_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.instance')),
            ],
        ),
        migrations.CreateModel(
            name='InstanceInstanceRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_instance_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.instanceinstanceconnection')),
                ('instance_object_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instance_object_1', to='apps.instance')),
                ('instance_object_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instance_object_2', to='apps.instance')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectPropertyRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_value', models.CharField(max_length=500)),
                ('instance_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.instance')),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.propertytype')),
            ],
        ),
    ]
