# Generated by Django 5.0 on 2023-12-26 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_merge_instance_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertytype',
            name='class_instance',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='apps.class'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='propertytype',
            name='raw_type',
            field=models.CharField(choices=[('string', 'String'), ('number', 'Integer'), ('float', 'Float'), ('boolean', 'Boolean'), ('date', 'Date'), ('markdown', 'Markdown'), ('image', 'Image'), ('file', 'File'), ('instance', 'Instance'), ('instance_list', 'Instance List')], max_length=100),
        ),
    ]
