# Generated by Django 5.0 on 2023-12-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_add_class_to_property_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertytype',
            name='limitation',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='propertytype',
            name='raw_type',
            field=models.CharField(choices=[('string', 'String'), ('number', 'Integer'), ('float', 'Float'), ('boolean', 'Boolean'), ('date', 'Date'), ('datetime', 'Date Time'), ('markdown', 'Markdown'), ('image', 'Image'), ('file', 'File'), ('instance', 'Instance'), ('instance_list', 'Instance List')], max_length=100),
        ),
    ]
