# Generated by Django 5.0.1 on 2024-02-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_remove_instance_instance_connection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertytype',
            name='raw_type',
            field=models.CharField(choices=[('string', 'String'), ('number', 'Integer'), ('float', 'Float'), ('boolean', 'Boolean'), ('date', 'Date'), ('datetime', 'Date Time'), ('markdown', 'Markdown'), ('image', 'Image'), ('file', 'File'), ('instance', 'Instance'), ('instance_list', 'Instance List'), ('json', 'JSON'), ('class', 'Class'), ('url', 'URL')], max_length=100),
        ),
    ]
